### PR TITLE
Add Ableton 11 support

### PR DESCRIPTION
**Pull request by laimison**

### CODE REVIEW

**Comment by lucianoiam** [comment]
Thanks for the PR. I would like to keep Live 10 (and 9) support and guess there should be an easy way to do it, given the patch only changes a single line of code. Will look into it later.

**Comment by laimison** [comment]
Sure, whatever suits you. Last resort could be `try` statement to import the lib needed for Live 10. Then set live_10 as true or false depening if `try` fails and use right filter in if statement.

**Comment by laimison** [comment]
@lucianoiam I have improved PR, updated README.md and tested Live 10 and Live 11 successfully using same `LiveRPyC` folder, exactly as in the PR. Works well.

How about reviewing this PR? You may want to merge it now and do your ideas later or decline a PR and do same goal in other way.

I have nothing else to add. So keep this as a final PR from me.

**Comment by lucianoiam** [comment]
Hey thanks again, I reworked the `filter` function issue in a simpler way and also assumed Live 11 in the README. If anyone needs support for an older version, the code is still compatible.


Closing the PR now.

**Comment by laimison** [comment]
Thanks, we have everything we need in place now. I switched my external code that uses live_rpyc to Ableton 11 without a hitch.

**Pull request closed without merging**
